version: '3.7'
services:
  web:
    build: ./taskmanager
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/taskmanager/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data:
